<feat>: <Добавить классы Item и User, для них сервисы, контроллеры и …
yncuk/java-shareit pull request #1
Opened 2023-02-10 14:19 UTC by yncuk

…хранилища в памяти>

2023-02-12 18:24 UTC, Donald522 requested changes
Привет!

Посмотрел, все по структуре хорошо, предложил некоторые моменты поправить.

2023-02-12 18:24 UTC, Donald522 commented on src/main/java/ru/practicum/shareit/exceptions/EntityBadRequest.java
> +public class EntityBadRequest extends Exception {
Лучше в конце тоже дописать Exception, чтобы следовать единой naming конвенции исключений

2023-02-12 18:24 UTC, Donald522 commented on src/main/java/ru/practicum/shareit/exceptions/handler/ErrorHandler.java
> +    public ErrorResponse handleInternalError(final InternalError e) {
Я бы тут скорее ловил просто Exception.
InternalError это что-то экзотическое. Вообще Error-ы нет смысла обрабатывать. После условного ООМ JVM требует рестарта.
А вот пропустить NPE или какой-нибудь датабазный эксепшн - запросто.

2023-02-12 18:24 UTC, Donald522 commented on src/main/java/ru/practicum/shareit/exceptions/EntityNotFoundException.java
> +public class EntityNotFoundException extends Exception {
Давай не будем наследоваться от checked исключения.
Наследуйся от Runtime. Checked исключения не используются в современных языках/фреймворках.

2023-02-12 18:24 UTC, Donald522 commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +    public Collection<ItemDto> findAll(@RequestHeader("X-Sharer-User-Id") int userId) throws EntityNotFoundException {
Тут соответственно надо будет убрать все `throws ...` после того, как будешь наследоваться от RuntimeException

2023-02-12 18:24 UTC, Donald522 commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +                                @RequestParam String text) throws EntityNotFoundException {
Тут форматирование съехало :)
Если пишешь в Idea, то сочетание Ctrl+Alt+L (command+option+L) отформатирует код

2023-02-12 18:24 UTC, Donald522 commented on src/main/java/ru/practicum/shareit/item/mapper/ItemMapper.java
> +        Collection<ItemDto> returnItems = new ArrayList<>();
Можно вот так написать
`return items.stream.map(ItemMapper::toItemDto).collect(toList())`
Короче выходит. Но дело вкуса.

2023-02-12 18:24 UTC, Donald522 commented on src/main/java/ru/practicum/shareit/item/model/Item.java
> +    @With
`@With` можно ставить над всем классом

2023-02-12 18:24 UTC, Donald522 commented on src/main/java/ru/practicum/shareit/item/service/ItemService.java
> +    Collection<ItemDto> findAll(Integer userId) throws EntityNotFoundException;
Тут тоже throws можно будет убрать

2023-02-12 18:24 UTC, Donald522 commented on src/main/java/ru/practicum/shareit/item/service/impl/ItemServiceImpl.java
> +        return ItemMapper.allToItemDto(itemStorage.findAll(userId));
Я больше люблю делать конвертацию в dto на уровне контроллера. 
На мой взгляд dto и его формат - это логика транспортного уровня, а не сервисного. 
Представь, что у твоего сервиса появится еще один потребитель и ему нужен будет функционал этого класса, но при этом у него будет свой dto (например в другом формате). В таком случае, логичнее (на мой взгляд) будет сделать 2 разных dto и 2 разных маппера из класса Item в эти 2 разные dto.
Но насколько я понимаю, эти интерфейсы пришли из заготовки уже, поэтому не буду просить это переделать, просто знай, что есть альтернативный путь.

2023-02-12 18:24 UTC, Donald522 commented on src/main/java/ru/practicum/shareit/item/service/impl/ItemServiceImpl.java
> +        if (itemDto.getAvailable() == null || itemDto.getName().isBlank() || itemDto.getName() == null ||
Такую валидацию лучше сделать в контроллере.
Обычно такие проверки автогенерятся (можешь например почитать про openapi spec) и программисту не надо писать их в своем коде. Но поскольку мы пока учимся и пишем такие вещи сами, то давай перенесем в контроллер.

2023-02-12 18:24 UTC, Donald522 commented on src/main/java/ru/practicum/shareit/item/storage/InMemoryItemStorage.java
> +        if (items.get(userId) == null) {
Дважды делаем get
Всегда лучше положить результат вызова (тем более потенциально удаленного) в отдельную переменную и работать с ней.

2023-02-12 18:24 UTC, Donald522 commented on src/main/java/ru/practicum/shareit/item/storage/InMemoryItemStorage.java
> +        item = item.withId(id);
Не увидел нигде, чтобы мы проставляли в Item поле owner

2023-02-12 18:24 UTC, Donald522 commented on src/main/java/ru/practicum/shareit/item/storage/InMemoryItemStorage.java
> +    public List<Item> search(Integer userId, String text) {
Зачем userId передается сюда?

2023-02-12 18:24 UTC, Donald522 commented on src/main/java/ru/practicum/shareit/item/storage/InMemoryItemStorage.java
> +    public Item findById(Integer userId, Integer itemId) throws EntityNotFoundException {
1. Зачем userId?
2. Смысл поиска по id в том, что это работает очень быстро. А тут нам приходится проходить по всей мапе, чтобы превратить ее в список
То есть хочется, чтобы сложность поиска по id была О(1), а у нас она О(кол-во пользователей)

2023-02-12 18:24 UTC, Donald522 commented on src/main/java/ru/practicum/shareit/user/UserController.java
> +    public UserDto create(@Valid @RequestBody User user) throws ConflictException {
Принимать надо тоже dto объект

2023-02-12 18:24 UTC, Donald522 commented on src/main/java/ru/practicum/shareit/user/service/impl/UserServiceImpl.java
> +        for (User currentUser : userStorage.findAll()) {
Это явно логика хранилища.
Представь, что у тебя используется база. Ты же не станешь делать select *, чтобы поискать совпадения по email?
В базе скорее всего на email будет повешен unique constraint, что по сути является уникальным индексом.
В in-memory реализации хранилища, это можно сделать с помощью мапы.

А так мы сделали операцию создания пользователя линейной по сложности от кол-ва пользователей.
На практике это означает то, что система не масштабируется на широкую аудиторию. Если вдруг сервис станет популярным, то регистрация каждого нового пользователя будет тяжелее предыдущей.

2023-02-12 18:24 UTC, Donald522 commented on src/main/java/ru/practicum/shareit/user/storage/InMemoryUserStorage.java
> +    public void delete(Integer userId) {
Удаление пользователя предложил бы сделать с помощью soft delete.
Это когда мы не удаляем сущность, а просто помечаем ее как удаленную.

Наверняка видел такое в разных соц. сетях. Когда страница пользователя якобы удалена, но его комментарии в группах и ваша с ним история переписки сохранена.

2023-02-12 18:24 UTC, Donald522 commented on src/test/java/ru/practicum/shareit/user/UserControllerTest.java
> +    @Order(1)
А зачем порядок тестам?

2023-02-13 08:21 UTC, yncuk commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +                                @RequestParam String text) throws EntityNotFoundException {
Привет, это я перенес, чтобы в столбик было и не слишком длинно, автоматическое форматирование кода использую, да)

2023-02-13 08:31 UTC, yncuk commented on src/main/java/ru/practicum/shareit/item/mapper/ItemMapper.java
> +        Collection<ItemDto> returnItems = new ArrayList<>();
Со стримами у нас толком не было работы, сказали включат в конце, изменят раздел с ними, подробнее все покажут

2023-02-13 11:41 UTC, yncuk commented on src/main/java/ru/practicum/shareit/item/storage/InMemoryItemStorage.java
> +    public List<Item> search(Integer userId, String text) {
действительно не за чем)

2023-02-13 17:49 UTC, yncuk commented on src/main/java/ru/practicum/shareit/item/service/impl/ItemServiceImpl.java
> +        return ItemMapper.allToItemDto(itemStorage.findAll(userId));
Да, звучит логично

2023-02-13 18:04 UTC, yncuk commented on src/test/java/ru/practicum/shareit/user/UserControllerTest.java
> +    @Order(1)
Больше для красоты и порядка сделал

2023-02-13 18:05 UTC, yncuk commented on src/main/java/ru/practicum/shareit/user/service/impl/UserServiceImpl.java
> +        for (User currentUser : userStorage.findAll()) {
Да, понимаю, временно вынес, пока базы данных нет

2023-02-13 18:08 UTC, yncuk commented on src/main/java/ru/practicum/shareit/user/service/impl/UserServiceImpl.java
> +        for (User currentUser : userStorage.findAll()) {
Предлагаешь сделать дополнительную мапу вида <Email, User> ?

2023-02-13 18:55 UTC, yncuk commented on src/main/java/ru/practicum/shareit/item/model/Item.java
> +    @With
если ставить над всем классом, проверка на гите ругается на стринговые поля
`Error:  High: Comparison of String parameter using == or != in ru.practicum.shareit.item.model.Item.withDescription(String) [ru.practicum.shareit.item.model.Item] At Item.java:[line 13] ES_COMPARING_PARAMETER_STRING_WITH_EQ
Error:  High: Comparison of String parameter using == or != in ru.practicum.shareit.item.model.Item.withName(String) [ru.practicum.shareit.item.model.Item] At Item.java:[line 12] ES_COMPARING_PARAMETER_STRING_WITH_EQ`

2023-02-13 19:01 UTC, yncuk commented on src/test/java/ru/practicum/shareit/user/UserControllerTest.java
> +    @Order(1)
по теме порядка тестов есть вопрос, в IDEA тесты разных классов не зависят друг от друга, а при проверке этих тестов на гите, они в одном ране запускаются в алфавитном порядке, создаются в хранилище Users из тестов ItemControllerTest, а потом Users из тестов UserControllerTest, как то можно сделать в IDEA, чтобы было как в гите?

2023-02-15 21:51 UTC, Donald522 commented on src/main/java/ru/practicum/shareit/item/mapper/ItemMapper.java
> +        Collection<ItemDto> returnItems = new ArrayList<>();
Со стримами главное не увлекаться. Часто вижу, как их используют, когда не надо. В итоге получается сложнее, чем было бы без них. Это не серебряная пуля.

2023-02-15 22:00 UTC, Donald522 commented on src/main/java/ru/practicum/shareit/item/storage/InMemoryItemStorage.java
> +        item = item.withOwner(userId);
Лучше бы в маппере конечно проставить owner-а

2023-02-15 22:00 UTC, Donald522 commented on src/main/java/ru/practicum/shareit/user/service/impl/UserServiceImpl.java
> +        for (User currentUser : userStorage.findAll()) {
Кажется в данном случае достаточно будет даже `Set<Email>`

2023-02-15 22:00 UTC, Donald522 commented on src/test/java/ru/practicum/shareit/user/UserControllerTest.java
> +    @Order(1)
Тут надо в другую сторону смотреть.
Тест должен работать независимо от того, в каком порядке он запускается.
Для этого тест перед началом своей работы должен все почистить, либо после себя. Либо и до и после)

Бывают случаи, когда в коде теста это сделать не получается. Для такого придумали в спринге аннотацию DirtiesContext, она заставляет контекст теста обновиться. Это замедляет тесты.

2023-02-15 22:01 UTC, Donald522 approved these changes
Привет!

Сейчас все нормально, думаю оптимизацию с email делать смысла особо нет, все равно база дальше будет.

2023-02-22 09:12 UTC, merged