<feat>: <Добавить ItemRequest и покрыть тестами код>
yncuk/java-shareit pull request #3
Opened 2023-03-19 21:13 UTC by yncuk

2023-03-20 20:28 UTC, Donald522 requested changes
Привет!

Работа хорошая, мне по большому счету не к чему придраться, поэтому все комментарии по мелочи.

2023-03-20 20:28 UTC, Donald522 commented on src/main/java/ru/practicum/shareit/request/controller/ItemRequestController.java
> +    private final String headerUserId = "X-Sharer-User-Id";
Константы заводятся обычно как private final static и называются в came case: HEADER_USER_ID

2023-03-20 20:28 UTC, Donald522 commented on src/main/java/ru/practicum/shareit/request/repository/ItemRequestRepository.java
> +    Collection<ItemRequest> findAllWithoutPropertyThisUser(Integer requesterId);
Я бы назвал как-нибудь получше метод

2023-03-20 20:28 UTC, Donald522 commented on src/main/java/ru/practicum/shareit/request/service/impl/ItemRequestServiceImpl.java
> +    public Collection<ItemRequestDto> findAll(int requesterId, Integer from, Integer size) {
Тут в названии метода тоже лучше отразить то, что мы исключаем запросы от requestorId
Это очень неочевидно с первого взгляда.

2023-03-20 20:28 UTC, Donald522 commented on src/main/resources/schema.sql
> +    REQUESTER_ID    INTEGER,
думаю по этой колонке имеет смысл сделать индекс

2023-03-20 20:28 UTC, Donald522 commented on src/test/java/ru/practicum/shareit/item/ItemControllerTest.java
> +    @Order(19)
А зачем порядок тестам задавать?
По-хорошему, тесты должны уметь работать в любом порядке и не влиять друг на друга. Если это не так - это проблема.

2023-03-21 16:50 UTC, yncuk commented on src/test/java/ru/practicum/shareit/item/ItemControllerTest.java
> +    @Order(19)
Тесты поправил

2023-03-22 13:55 UTC, Donald522 approved these changes
Привет!

Не очень понял про индекс - если ты решил не делать то ок, но если ты пытался его сделать конструкций constraint reference то это неверно (если только h2 не создает неявно индекс на внешние ключи). Но даже так, явное всегда лучше неявного.

2023-03-22 13:55 UTC, Donald522 commented on src/main/resources/schema.sql
> +        unique,
первичный ключ всегда уникален, дописывать unique не нужно

2023-03-22 13:55 UTC, Donald522 commented on src/main/resources/schema.sql
> +        constraint item_request_users_user_id_fk
Если это была попытка сделать индекс, то это не индекс :)
Индекс создается через create index ...

2023-03-23 19:30 UTC, yncuk commented on src/main/resources/schema.sql
> +        constraint item_request_users_user_id_fk
такое один раз в практикуме упоминалось, в тестах ругается на этот индекс, что он уже создан, то есть h2 неявно создает

2023-03-23 19:48 UTC, merged